# Generated by Django 3.0.5 on 2020-05-05 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackdefault',
            name='course',
        ),
        migrations.CreateModel(
            name='FeedbackTA',
            fields=[
                ('feedbackdefault_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.FeedbackDefault')),
                ('TA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('forms.feedbackdefault',),
        ),
        migrations.CreateModel(
            name='FeedbackProf',
            fields=[
                ('feedbackdefault_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.FeedbackDefault')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('forms.feedbackdefault',),
        ),
        migrations.CreateModel(
            name='FeedbackCourse',
            fields=[
                ('feedbackdefault_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.FeedbackDefault')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Course')),
            ],
            bases=('forms.feedbackdefault',),
        ),
    ]
