# Generated by Django 3.0.5 on 2020-05-05 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0002_auto_20200505_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prof',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prof_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='tas',
            field=models.ManyToManyField(related_name='ta_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='student_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
