# Generated by Django 3.0.5 on 2020-05-05 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0003_auto_20200505_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prof',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
