# Generated by Django 3.0.5 on 2020-05-06 06:34

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20200505_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=forms.models.current_year),
        ),
    ]
