version: "2.4"

services:
  vue:
    image: sa-vue
    build: ./vue
    ports:
      - '8001:8001'
    volumes:
      - './vue/index.html:/app/index.html'
      - './vue/src:/app/src'
      - './vue/static:/app/static'

  nginx:
    image: sa-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - "sockets:/tmp/sockets"


  web:
    image: argus-web
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        BASE_DIR: ./web
    environment:
      UWSGI_PROCESSES: 1
      UWSGI_THREADS: 2
      UWSGI_HARAKIRI: 60
      UWSGI_MAX_REQUESTS: 100
    volumes:
      - "sockets:/tmp/sockets"
      - "./web:/application"

volumes:
  sockets:
