version: "3"

services:
  vue:
    image: sa-vue
    build: ./vue
    ports:
      - '8001:8001'
    volumes:
      - "./vue/src:/app/src"

  django:
    build:
      context: web
      dockerfile: Dockerfile.dev
    image: sa-django
    volumes:
      - "./web:/app"
      - "sockets:/tmp/sockets"
      - "./data:/var/data"
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_APP_NAME: "sa"
      DJANGO_SECRET_KEY: "khwfwtspowlhf7mk8jekzz6wny5aa1sztt"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      DJANGO_DATABASE_NAME: "pgdb"
      DJANGO_DATABASE_USER: "pguser"
      DJANGO_DATABASE_PASSWORD: "pgpassword"
      DJANGO_DATABASE_HOST: "postgres"
      DJANGO_DATABASE_PORT: "5432"
      UWSGI_PROCESSES: "2"
      UWSGI_THREADS: "2"
      UWSGI_HARAKIRI: "60"
      UWSGI_MAX_REQUESTS: "100"
    depends_on:
      - postgres
    restart: "no"

  postgres:
    image: "postgres:12"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_DB=pgdb"
      - "POSTGRES_USER=pguser"
      - "POSTGRES_PASSWORD=pgpassword"
    restart: "no"

volumes:
  postgres-data:
  sockets:
