version: "2.4"

services:
  nginx:
    image: sa-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile.prod
    ports:
      - '8080:8080'
    volumes:
      - "sockets:/tmp/sockets"

  web:
    image: sa-web
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        BASE_DIR: ./web
    environment:
      UWSGI_PROCESSES: 1
      UWSGI_THREADS: 2
      UWSGI_HARAKIRI: 60
      UWSGI_MAX_REQUESTS: 100
    volumes:
      - "sockets:/tmp/sockets"
      - "./web:/application"

  db:
    image: mongo:latest
    container_name: 'mongodb'
    volumes:
      - $DATABASE_PATH:/data/db

volumes:
  sockets: