FROM node:11-alpine as vue

ARG CONTEXT=vue

WORKDIR /app

COPY ./$CONTEXT ./

RUN sh /app/docker-entrypoint.sh

RUN npm run build


FROM nginx:1.15.8

ARG CONTEXT=nginx

COPY $CONTEXT/prod-config /etc/nginx

COPY --from=vue /app/dist /app

EXPOSE "8080"

VOLUME ["/tmp/sockets"]